import Head from "next/head";
import Container from "@accordion/layout/Container";
import Page from "@accordion/layout/Page";
import HomeView from "@accordion/views/HomeView";

export default function Home() {
  return (
    <>
      <Head>
        <title>Accordion Pattern</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <main>
          <Container>
            <HomeView />
          </Container>
        </main>
      </Page>
    </>
  );
}
